all: compile

include ../../mk/debug.mk
include ../../mk/browserify.mk

.PHONY: compile
compile: browserify.mk-compile

.PHONY: depend
depend: browserify.mk-depend

.PHONY: clean
clean: browserify.mk-clean
